# Generated by Django 4.2 on 2024-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0015_remove_paymenttermsupdates_interested_to_continue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialperiod',
            name='interested_in_buying',
            field=models.IntegerField(default=0),
        ),
    ]
